[package]
name = "macrosia"
version = "0.2.5"
edition = "2024"

[dependencies]
seahash = "4"
regex = "1"
num-complex = "0.4"
itertools = "0.14"
const_format = "0.2"
stacker = "0.1"
rand = {version = "0.9", default-features = false, features = ["std", "thread_rng"]}
base64 = "0.22"
web-time = {version = "1"}
getrandom = { version = "0.3.3", features = ["wasm_js"], optional = true }
flate2 = { version = "1.0.17", features = ["zlib-rs"], default-features = false }
aho-corasick = "1"
rand_xoshiro = "0.7"

[features]
default = []
wasm = ["dep:getrandom"]
catch-panic = []
